# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BlUJL7SE89N6R4y4cbRDFI46wHiPPhvU
"""

def my_lists(keys,values):
 if len(keys)==len(values):
  return dict(zip(keys,values))
 else:
  return "error lists must have the same length"