# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YcVbFYNt_uCRP_54xoBpTdq_Gir_eQRy
"""

name = 'Takoua'
Surname = "Soltani"
print(name)
print(Surname)
age= '21'
print(age)

5 + 1
5 * 5
24 / 5
25 // 3
10 % 3
5 ** 2
2 ** 7

p = "Python"
c = "Coding"

try:
    print(p[6])
except IndexError as e:
    print(e)

print(repr(p[6:]))

print(p[::-1])

p += c
print(p)

p = "Mython"
try:
    p[0] = "P"
except TypeError as e:
    print(e)

p = "P" + p[1:]
print(p)

rgb = ["R", "G", "B"]
rgb_copy = rgb
rgb_copy.append("A")

print(rgb_copy)
print(rgb)
print(id(rgb) == id(rgb_copy))

rgb = ["R", "G", "B"]
correct_rgb_copy = rgb[:]
correct_rgb_copy.append("A")

print(correct_rgb_copy)
print(rgb)
print(id(rgb) == id(correct_rgb_copy))

numbers = [-3, 5, -1, 7, 0, -8, 10]

count = 0
for num in numbers:
    if num > 0:
        count += 1

print("Count of positive numbers:", count)

def filter_even_numbers(numbers):
    """
    Returns a list of even numbers from a list.
    """
    result = []
    for number in numbers:
        if number % 2 == 0:
            result.append(number)
    return result


test = [1, 2, 3, 4, 5, 6, 7, 8]
print(filter_even_numbers(test))

students = ["Alice", "Bob", "Charlie", "David", "Eve"]
grades = [85, 90, 78, 92, 90]

unique_grades = set(grades)

highest_grade = max(grades)

student_grades = dict(zip(students, grades))

top_students = [student for student, grade in student_grades.items() if grade == highest_grade]

print("Student Grades Dictionary:", student_grades)
print("Unique Grades Set:", unique_grades)
print("Highest Grade:", highest_grade)
print("Top Student(s):", top_students)