# -*- coding: utf-8 -*-
"""tp01.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLebg1h5t0Dl5UXvY-bV-46mCPwcacHm
"""

from main import my_lists
keys=["pizza","tacos","pasta"]
values = [1200 ,800, 900]
resto_menu= my_lists(keys, values)
print(resto_menu)