# -*- coding: utf-8 -*-
"""tp2ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kbO_7tTctuUtjwETSTUTgGCtnIGbjccd
"""

import numpy as np
arr = np.arange(10, 51, 5)
print("Array:", arr)
sub_arr = arr[2:6]
print("Sliced Array (index 2 to 5):", sub_arr)
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))
matrix = np.array([[1, 2, 3], [4, 5, 6]])
element = matrix[1, 2]
print("Matrix:\n", matrix)
print("Element at row 1, col 2:", element)

import pandas as pd
fruits = pd.Series([5.0, 3.5, 8.0, 12.0, 6.5], index=['Apple', 'Banana', 'Cherry', 'Mango', 'Orange'])
print("Fruits Series:\n", fruits)
third_fruit_price = fruits.iloc[2]
print("\nPrice of 3rd fruit:", third_fruit_price)
fruits_updated = fruits * 1.1
print("\nUpdated Prices (+10%):\n", fruits_updated)
print("\nAverage Price:", fruits.mean())
print("Most Expensive Fruit:", fruits.idxmax(), "with price:", fruits.max())

import pandas as pd
data = {
    'Student': ['Ahmed', 'Sara', 'Omar', 'Laila', 'Khaled'],
    'Math': [85, 92, 78, 88, 95],
    'English': [88, 79, 82, 90, 84],
    'Science': [90, 85, 80, 93, 89]
}
df_students = pd.DataFrame(data)
print("First 3 rows:\n", df_students.head(3))
print("\nMath Scores:\n", df_students['Math'])
math_above_80 = df_students[df_students['Math'] > 80]
print("\nStudents with Math > 80:\n", math_above_80)
both_above_85 = df_students[(df_students['Math'] > 85) & (df_students['English'] > 85)]
print("\nStudents with Math > 85 AND English > 85:\n", both_above_85)

import pandas as pd

sales_data = {
    'Product': ['A', 'B', 'A', 'C', 'B', 'C', 'A', 'B'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'West', 'East'],
    'Sales': [150, 200, 300, 400, 250, 100, 180, 310]
}
df_sales = pd.DataFrame(sales_data)
total_sales_by_product = df_sales.groupby('Product')['Sales'].sum()
print("Total Sales by Product:\n", total_sales_by_product)
avg_sales_by_region = df_sales.groupby('Region')['Sales'].mean()
print("\nAverage Sales by Region:\n", avg_sales_by_region)
agg_product_sales = df_sales.groupby('Product')['Sales'].agg(['mean', 'max'])
print("\nMean and Max Sales by Product:\n", agg_product_sales)

import pandas as pd
import matplotlib.pyplot as plt

revenue_data = {
    'Quarter': ['Q1', 'Q2', 'Q3', 'Q4'],
    'Revenue': [12000, 15000, 18000, 22000]
}
df_revenue = pd.DataFrame(revenue_data)

df_revenue.plot(x='Quarter', y='Revenue', kind='line', marker='o')
plt.title('Quarterly Revenue Line Plot')
plt.xlabel('Quarter')
plt.ylabel('Revenue ($)')
plt.show()

df_revenue.plot(x='Quarter', y='Revenue', kind='bar', color='skyblue')
plt.title('Quarterly Revenue Bar Chart')
plt.xlabel('Quarter')
plt.ylabel('Revenue ($)')
plt.xticks(rotation=0)
plt.show()

scores_data = {'Scores': [55, 62, 68, 72, 75, 78, 81, 85, 88, 90, 92, 95, 98]}
df_scores = pd.DataFrame(scores_data)

df_scores['Scores'].plot(kind='hist', bins=5, edgecolor='black', color='orange')
plt.title('Distribution of Student Test Scores')
plt.xlabel('Score')
plt.ylabel('Frequency')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv'
iris_df = pd.read_csv(url)

virginica_df = iris_df[iris_df['species'] == 'virginica']
print("First 5 rows of Virginica:\n", virginica_df.head())

min_petal_width = iris_df['petal_width'].min()
max_petal_width = iris_df['petal_width'].max()
print(f"\nPetal Width: Min = {min_petal_width}, Max = {max_petal_width}")

highest_avg_sepal = iris_df.groupby('species')['sepal_length'].mean().idxmax()
print(f"\nSpecies with highest avg sepal length: {highest_avg_sepal}")

iris_df.plot(x='petal_length', y='petal_width', kind='scatter', figsize=(8, 5))
plt.title('Petal Length vs Petal Width')
plt.xlabel('Petal Length (cm)')
plt.ylabel('Petal Width (cm)')
plt.show()
iris_df.groupby('species')['petal_length'].mean().plot(kind='bar', figsize=(8, 5), color='green')
plt.title('Average Petal Length by Species')
plt.xlabel('Species')
plt.ylabel('Average Petal Length (cm)')
plt.xticks(rotation=0)
plt.show()